---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nodjs-app
  name: nodjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nodjs-app
  template:
    metadata:
      labels:
        run: nodjs-app
    spec:
      containers:
      - image: gcr.io/steady-adapter-346414/nodjs-app:latest
        name: nodjs-app
        command: ["node"]
        args: ["server.js"]
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
               
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
 metadata:
    name: nodjs-app1
  spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: nodjs-app
    minReplicas: 1
    maxReplicas: 5
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80 
     - type: Resource
       resource:
         name: memory
         target:
           type: AverageValue
           averageValue: 30Mi
