apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nodjs-app
  name: nodjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nodjs-app
  template:
    metadata:
      labels:
        run: nodjs-app
    spec:
      containers:
      - image: gcr.io/steady-adapter-346414/nodjs-app:latest
        name: nodjs-app
        command: ["node"]
        args: ["server.js"]
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
