apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
 metadata:
    name: nodjs-app
  spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: nodjs-app
    minReplicas: 1
    maxReplicas: 5
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80 
     - type: Resource
       resource:
         name: memory
         target:
           type: AverageValue
           averageValue: 30Mi
